# Generated by Django 4.2.4 on 2024-03-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, null=True)),
                ("message", models.TextField(null=True)),
            ],
        ),
    ]
